app:
  jwt.secret: JKHIbhfg67stdfsdfy767tfsdfuyt8fsdyf

server:
  port: 8080

spring:
  security:
    basic:
      enabled: false
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/kotlin
    user: user
    password: password
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    initialize: true
    continue-on-error: true

